-- CREATE DATABASE CONTROLE_VACINAS;

CREATE TABLE USERS (
    ID_USER INT AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    CONSTRAINT PK_USERS_ID_USER PRIMARY KEY (ID_USER)
);

CREATE TABLE VACCINATIONS (
    ID_VACCINATION INT AUTO_INCREMENT,
    VACCINE_NAME VARCHAR(255) NOT NULL,
    USER_EMAIL VARCHAR(150) NOT NULL,
    CONSTRAINT PK_VACCINATIONS_ID_VACCINATION PRIMARY KEY (ID_VACCINATION),
    CONSTRAINT FK_VACCINATIONS_USER_EMAIL FOREIGN KEY (USER_EMAIL) REFERENCES USERS(EMAIL)
);
